services:
  - type: web
    name: ai-checker-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GITHUB_TOKEN
        sync: false
